# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='D:\\College_project\\UnistashFinal\\static\\static\\abc1.jpg', upload_to=b''),
        ),
    ]
