# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-27 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0008_auto_20170824_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='static\x07bc1.jpg', upload_to=b''),
        ),
    ]
