# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-27 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0009_auto_20170827_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='static\x07bc1.jpg', null=True, upload_to=b''),
        ),
    ]
