# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-27 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0010_auto_20170827_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
