# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0012_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(upload_to=b''),
        ),
    ]
