# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0013_auto_20170828_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(default='oppo', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='main_file',
            field=models.FileField(upload_to=b''),
        ),
    ]
