# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0014_auto_20170828_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
