# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0020_contribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribute',
            name='upload_file',
            field=models.FileField(default='abc.jpg', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
