# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0021_contribute_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribute',
            name='subject_code',
            field=models.CharField(default='bit56', max_length=200),
            preserve_default=False,
        ),
    ]
