# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-31 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0022_contribute_subject_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='profile_photo',
        ),
    ]
