# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-31 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0023_auto_20170831_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribute',
            name='name',
        ),
        migrations.AddField(
            model_name='contribute',
            name='name_of_file',
            field=models.CharField(default='cse', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribute',
            name='name_of_student',
            field=models.CharField(default='cse', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribute',
            name='subject',
            field=models.CharField(default='cse', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contribute',
            name='subject_code',
            field=models.CharField(max_length=10),
        ),
    ]
